/**
 * Complete BarTender-Class Barcode Symbology Catalog
 * All 84 requested industrial symbologies registered with capability states,
 * default validation patterns, character sets, and printer language support.
 */

import { BarcodeSymbologyDefinition } from '../types';

export const BARCODE_SYMBOLOGIES: BarcodeSymbologyDefinition[] = [
  // --- 1D Linear ---
  {
    id: 'code128',
    name: 'Code 128',
    aliases: ['Code 128 Auto', 'ISBT 128'],
    category: 'Linear 1D',
    dimension: '1D',
    defaultData: 'LF-88429-A',
    supportsVariableData: true,
    supportsHumanReadableText: true,
    supportsChecksum: true,
    supportsGS1: true,
    supportsErrorCorrection: false,
    capability: 'SUPPORTED',
    printerLanguages: ['ZPL', 'TSPL', 'EPL', 'CPCL'],
    description: 'High-density variable-length alphanumeric symbology with automated subsets A/B/C and Mod-103 checksum.',
    characterSetHint: 'All 128 ASCII characters',
  },
  {
    id: 'code39',
    name: 'Code 39 (Regular)',
    aliases: ['USD-3', '3 of 9', 'LOGMARS'],
    category: 'Linear 1D',
    dimension: '1D',
    defaultData: 'PART-9042',
    supportsVariableData: true,
    supportsHumanReadableText: true,
    supportsChecksum: true,
    supportsGS1: false,
    supportsErrorCorrection: false,
    capability: 'SUPPORTED',
    printerLanguages: ['ZPL', 'TSPL', 'EPL', 'CPCL'],
    description: 'Industrial discrete barcode widely used in DoD, automotive, and warehouse inventory.',
    characterSetHint: 'A-Z, 0-9, and symbols - . $ / + % space',
  },
  {
    id: 'code39full',
    name: 'Code 39 (Full ASCII)',
    aliases: ['Extended 39'],
    category: 'Linear 1D',
    dimension: '1D',
    defaultData: 'Item*#402',
    supportsVariableData: true,
    supportsHumanReadableText: true,
    supportsChecksum: true,
    supportsGS1: false,
    supportsErrorCorrection: false,
    capability: 'SUPPORTED',
    printerLanguages: ['ZPL', 'TSPL', 'EPL'],
    description: 'Full 128-character ASCII encoding using two-character sequences in Code 39.',
  },
  {
    id: 'code93',
    name: 'Code 93',
    aliases: ['USS-93'],
    category: 'Linear 1D',
    dimension: '1D',
    defaultData: 'CODE93-DATA',
    supportsVariableData: true,
    supportsHumanReadableText: true,
    supportsChecksum: true,
    supportsGS1: false,
    supportsErrorCorrection: false,
    capability: 'SUPPORTED',
    printerLanguages: ['ZPL', 'TSPL'],
    description: 'High-density continuous symbology with dual check characters C and K.',
  },
  {
    id: 'code93i',
    name: 'Code 93i',
    aliases: ['Inverted 93'],
    category: 'Linear 1D',
    dimension: '1D',
    defaultData: '93I-88210',
    supportsVariableData: true,
    supportsHumanReadableText: true,
    supportsChecksum: true,
    supportsGS1: false,
    supportsErrorCorrection: false,
    capability: 'PARTIAL',
    printerLanguages: ['ZPL'],
    description: 'Inverted modulation variant of Code 93 for specialized scanning systems.',
  },
  {
    id: 'codabar',
    name: 'Codabar',
    aliases: ['NW-7', 'Ames Code', 'Monarch'],
    category: 'Linear 1D',
    dimension: '1D',
    defaultData: 'A12345678B',
    supportsVariableData: true,
    supportsHumanReadableText: true,
    supportsChecksum: false,
    supportsGS1: false,
    supportsErrorCorrection: false,
    capability: 'SUPPORTED',
    printerLanguages: ['ZPL', 'TSPL', 'EPL'],
    description: 'Used in blood banks, libraries, and express air freight. Uses start/stop delimiters A, B, C, D.',
  },
  {
    id: 'interleaved2of5',
    name: 'Interleaved 2 of 5',
    aliases: ['ITF', 'I-2/5'],
    category: 'Linear 1D',
    dimension: '1D',
    defaultData: '9081234567',
    supportsVariableData: true,
    supportsHumanReadableText: true,
    supportsChecksum: true,
    supportsGS1: false,
    supportsErrorCorrection: false,
    capability: 'SUPPORTED',
    printerLanguages: ['ZPL', 'TSPL', 'EPL', 'CPCL'],
    description: 'High-density numeric-only barcode encoding pairs of digits in interleaved bars and spaces.',
    characterSetHint: 'Even number of numeric digits (0-9)',
  },
  {
    id: 'itf14',
    name: 'ITF-14',
    aliases: ['Case Code', 'SCC-14'],
    category: 'Retail & ISBN',
    dimension: '1D',
    defaultData: '10012345678902',
    supportsVariableData: true,
    supportsHumanReadableText: true,
    supportsChecksum: true,
    supportsGS1: true,
    supportsErrorCorrection: false,
    capability: 'SUPPORTED',
    printerLanguages: ['ZPL', 'TSPL'],
    description: 'GS1 standard packaging container case barcode with protective bearer bars.',
    characterSetHint: 'Exactly 14 numeric digits',
  },
  {
    id: 'upca',
    name: 'UPC-A',
    aliases: ['Universal Product Code'],
    category: 'Retail & ISBN',
    dimension: '1D',
    defaultData: '012345678905',
    supportsVariableData: true,
    supportsHumanReadableText: true,
    supportsChecksum: true,
    supportsGS1: true,
    supportsErrorCorrection: false,
    capability: 'SUPPORTED',
    printerLanguages: ['ZPL', 'TSPL', 'EPL'],
    description: 'Standard retail point-of-sale barcode for North American consumer products.',
    characterSetHint: '11 or 12 numeric digits',
  },
  {
    id: 'upce',
    name: 'UPC-E',
    aliases: ['Zero-suppressed UPC'],
    category: 'Retail & ISBN',
    dimension: '1D',
    defaultData: '01234565',
    supportsVariableData: true,
    supportsHumanReadableText: true,
    supportsChecksum: true,
    supportsGS1: true,
    supportsErrorCorrection: false,
    capability: 'SUPPORTED',
    printerLanguages: ['ZPL', 'TSPL'],
    description: 'Compact zero-suppressed variant of UPC-A for small packaging items.',
  },
  {
    id: 'ean13',
    name: 'EAN-13',
    aliases: ['GTIN-13', 'International Article Number'],
    category: 'Retail & ISBN',
    dimension: '1D',
    defaultData: '5901234123457',
    supportsVariableData: true,
    supportsHumanReadableText: true,
    supportsChecksum: true,
    supportsGS1: true,
    supportsErrorCorrection: false,
    capability: 'SUPPORTED',
    printerLanguages: ['ZPL', 'TSPL', 'EPL'],
    description: 'Worldwide retail trade item numbering barcode with Mod-10 check digit.',
    characterSetHint: '12 or 13 numeric digits',
  },
  {
    id: 'ean8',
    name: 'EAN-8',
    aliases: ['GTIN-8'],
    category: 'Retail & ISBN',
    dimension: '1D',
    defaultData: '96385074',
    supportsVariableData: true,
    supportsHumanReadableText: true,
    supportsChecksum: true,
    supportsGS1: true,
    supportsErrorCorrection: false,
    capability: 'SUPPORTED',
    printerLanguages: ['ZPL', 'TSPL'],
    description: 'Compact 8-digit international barcode for small packaging.',
  },
  {
    id: 'jan13',
    name: 'JAN-13',
    aliases: ['Japanese Article Number 13'],
    category: 'Retail & ISBN',
    dimension: '1D',
    defaultData: '4901234567894',
    supportsVariableData: true,
    supportsHumanReadableText: true,
    supportsChecksum: true,
    supportsGS1: true,
    supportsErrorCorrection: false,
    capability: 'SUPPORTED',
    printerLanguages: ['ZPL', 'TSPL'],
    description: 'Standard Japanese retail product barcode (45 or 49 country prefix).',
  },
  {
    id: 'jan8',
    name: 'JAN-8',
    aliases: ['Japanese Article Number 8'],
    category: 'Retail & ISBN',
    dimension: '1D',
    defaultData: '49123456',
    supportsVariableData: true,
    supportsHumanReadableText: true,
    supportsChecksum: true,
    supportsGS1: true,
    supportsErrorCorrection: false,
    capability: 'SUPPORTED',
    printerLanguages: ['ZPL', 'TSPL'],
    description: 'Compact Japanese article barcode for small products.',
  },
  {
    id: 'isbn13',
    name: 'ISBN-13',
    aliases: ['Bookland EAN'],
    category: 'Retail & ISBN',
    dimension: '1D',
    defaultData: '9780306406157',
    supportsVariableData: true,
    supportsHumanReadableText: true,
    supportsChecksum: true,
    supportsGS1: true,
    supportsErrorCorrection: false,
    capability: 'SUPPORTED',
    printerLanguages: ['ZPL', 'TSPL'],
    description: 'International Standard Book Numbering barcode with 978 or 979 prefix.',
  },
  {
    id: 'dun14',
    name: 'DUN-14',
    aliases: ['Distribution Unit Number'],
    category: 'Retail & ISBN',
    dimension: '1D',
    defaultData: '15400141288763',
    supportsVariableData: true,
    supportsHumanReadableText: true,
    supportsChecksum: true,
    supportsGS1: true,
    supportsErrorCorrection: false,
    capability: 'SUPPORTED',
    printerLanguages: ['ZPL'],
    description: 'Distribution shipping container code based on Interleaved 2 of 5.',
  },
  {
    id: 'msi',
    name: 'MSI Plessey',
    aliases: ['Modified Plessey'],
    category: 'Linear 1D',
    dimension: '1D',
    defaultData: '1234567',
    supportsVariableData: true,
    supportsHumanReadableText: true,
    supportsChecksum: true,
    supportsGS1: false,
    supportsErrorCorrection: false,
    capability: 'SUPPORTED',
    printerLanguages: ['ZPL', 'TSPL'],
    description: 'Commonly used in supermarket shelf tag inventory management.',
  },
  {
    id: 'code11',
    name: 'Code 11',
    aliases: ['USD-8'],
    category: 'Linear 1D',
    dimension: '1D',
    defaultData: '123-456-78',
    supportsVariableData: true,
    supportsHumanReadableText: true,
    supportsChecksum: true,
    supportsGS1: false,
    supportsErrorCorrection: false,
    capability: 'SUPPORTED',
    printerLanguages: ['ZPL'],
    description: 'High-density numeric code primarily used for telecommunications equipment labelling.',
  },
  {
    id: 'standard2of5',
    name: 'Standard 2 of 5',
    aliases: ['Industrial 2 of 5', 'Discrete 2 of 5'],
    category: 'Linear 1D',
    dimension: '1D',
    defaultData: '135792468',
    supportsVariableData: true,
    supportsHumanReadableText: true,
    supportsChecksum: false,
    supportsGS1: false,
    supportsErrorCorrection: false,
    capability: 'SUPPORTED',
    printerLanguages: ['ZPL'],
    description: 'Low-density 2-of-5 discrete numeric linear symbology.',
  },
  {
    id: 'industrial2of5',
    name: 'Industrial 2 of 5',
    aliases: ['2 of 5 Industrial'],
    category: 'Linear 1D',
    dimension: '1D',
    defaultData: '987654321',
    supportsVariableData: true,
    supportsHumanReadableText: true,
    supportsChecksum: false,
    supportsGS1: false,
    supportsErrorCorrection: false,
    capability: 'SUPPORTED',
    printerLanguages: ['ZPL'],
    description: 'Used in airline ticketing and industrial document management.',
  },
  {
    id: 'iata2of5',
    name: 'IATA 2 of 5',
    aliases: ['Airline Baggage 2 of 5'],
    category: 'Linear 1D',
    dimension: '1D',
    defaultData: '0123456789',
    supportsVariableData: true,
    supportsHumanReadableText: true,
    supportsChecksum: true,
    supportsGS1: false,
    supportsErrorCorrection: false,
    capability: 'PARTIAL',
    printerLanguages: ['ZPL'],
    description: 'International Air Transport Association baggage handling standard.',
  },
  {
    id: 'matrix2of5',
    name: 'Matrix 2 of 5',
    aliases: ['Matrix 25'],
    category: 'Linear 1D',
    dimension: '1D',
    defaultData: '24680135',
    supportsVariableData: true,
    supportsHumanReadableText: true,
    supportsChecksum: true,
    supportsGS1: false,
    supportsErrorCorrection: false,
    capability: 'PARTIAL',
    printerLanguages: ['ZPL'],
    description: 'Matrix variation of the 2 of 5 family with fixed bar and space widths.',
  },
  {
    id: 'datalogic2of5',
    name: 'Datalogic 2 of 5',
    aliases: ['China Post linear'],
    category: 'Linear 1D',
    dimension: '1D',
    defaultData: '88776655',
    supportsVariableData: true,
    supportsHumanReadableText: true,
    supportsChecksum: true,
    supportsGS1: false,
    supportsErrorCorrection: false,
    capability: 'PARTIAL',
    printerLanguages: ['ZPL'],
    description: 'Italian postal and automatic sorting 2 of 5 variant.',
  },
  {
    id: 'nec2of5',
    name: 'NEC 2 of 5',
    aliases: ['Nippon Electric 2 of 5'],
    category: 'Linear 1D',
    dimension: '1D',
    defaultData: '33445566',
    supportsVariableData: true,
    supportsHumanReadableText: true,
    supportsChecksum: true,
    supportsGS1: false,
    supportsErrorCorrection: false,
    capability: 'PARTIAL',
    printerLanguages: ['ZPL'],
    description: 'Japanese electronic manufacturing tracking barcode.',
  },
  {
    id: 'telepen',
    name: 'Telepen',
    aliases: ['Telepen Alpha', 'Telepen Numeric'],
    category: 'Specialized',
    dimension: '1D',
    defaultData: 'TELEPEN-809',
    supportsVariableData: true,
    supportsHumanReadableText: true,
    supportsChecksum: true,
    supportsGS1: false,
    supportsErrorCorrection: false,
    capability: 'SUPPORTED',
    printerLanguages: ['ZPL'],
    description: 'UK library and academic identity standard encoding full ASCII without shift states.',
  },
  {
    id: 'ukplessey',
    name: 'UK Plessey',
    aliases: ['Plessey Code'],
    category: 'Linear 1D',
    dimension: '1D',
    defaultData: '123456AB',
    supportsVariableData: true,
    supportsHumanReadableText: true,
    supportsChecksum: true,
    supportsGS1: false,
    supportsErrorCorrection: false,
    capability: 'SUPPORTED',
    printerLanguages: ['ZPL'],
    description: 'Pulse-width modulated barcode originally developed in England.',
  },
  {
    id: 'opc',
    name: 'OPC',
    aliases: ['Optical Product Code'],
    category: 'Linear 1D',
    dimension: '1D',
    defaultData: 'OPC992211',
    supportsVariableData: true,
    supportsHumanReadableText: true,
    supportsChecksum: true,
    supportsGS1: false,
    supportsErrorCorrection: false,
    capability: 'RENDER_ONLY',
    printerLanguages: ['ZPL'],
    description: 'Used in retail optical, contact lens, and eyewear distribution.',
  },
  {
    id: 'nw7',
    name: 'NW-7',
    aliases: ['Japanese Codabar'],
    category: 'Linear 1D',
    dimension: '1D',
    defaultData: 'A4912345678B',
    supportsVariableData: true,
    supportsHumanReadableText: true,
    supportsChecksum: false,
    supportsGS1: false,
    supportsErrorCorrection: false,
    capability: 'SUPPORTED',
    printerLanguages: ['ZPL', 'TSPL'],
    description: 'Japanese standard term for Codabar with numeric content and framing chars.',
  },
  {
    id: 'upstracking',
    name: 'UPS Tracking',
    aliases: ['UPS MaxiCode linear', '1Z Code'],
    category: 'Linear 1D',
    dimension: '1D',
    defaultData: '1Z9999999999999999',
    supportsVariableData: true,
    supportsHumanReadableText: true,
    supportsChecksum: true,
    supportsGS1: false,
    supportsErrorCorrection: false,
    capability: 'SUPPORTED',
    printerLanguages: ['ZPL', 'EPL'],
    description: 'United Parcel Service 1Z tracking package linear Code 128 variant.',
  },
  {
    id: 'isscode128',
    name: 'ISS Code 128',
    aliases: ['International Standard Serial Code 128'],
    category: 'Linear 1D',
    dimension: '1D',
    defaultData: 'ISS-998822',
    supportsVariableData: true,
    supportsHumanReadableText: true,
    supportsChecksum: true,
    supportsGS1: false,
    supportsErrorCorrection: false,
    capability: 'SUPPORTED',
    printerLanguages: ['ZPL'],
    description: 'Standard serial code identification barcode variant.',
  },
  {
    id: 'uccean128',
    name: 'UCC/EAN-128',
    aliases: ['EAN 128 Legacy'],
    category: 'Linear 1D',
    dimension: '1D',
    defaultData: '(01)00012345678905',
    supportsVariableData: true,
    supportsHumanReadableText: true,
    supportsChecksum: true,
    supportsGS1: true,
    supportsErrorCorrection: false,
    capability: 'SUPPORTED',
    printerLanguages: ['ZPL', 'TSPL'],
    description: 'Predecessor designation to GS1-128 shipping identification standard.',
  },
  {
    id: 'circularcode39',
    name: 'Circular Code 39',
    aliases: ['Radial 39'],
    category: 'Linear 1D',
    dimension: '1D',
    defaultData: 'RADIAL39',
    supportsVariableData: false,
    supportsHumanReadableText: false,
    supportsChecksum: false,
    supportsGS1: false,
    supportsErrorCorrection: false,
    capability: 'RENDER_ONLY',
    printerLanguages: [],
    description: 'Circular/radial projection of Code 39 for cylindrical vials and test tubes.',
  },
  {
    id: 'circularcode93',
    name: 'Circular Code 93',
    aliases: ['Radial 93'],
    category: 'Linear 1D',
    dimension: '1D',
    defaultData: 'RADIAL93',
    supportsVariableData: false,
    supportsHumanReadableText: false,
    supportsChecksum: false,
    supportsGS1: false,
    supportsErrorCorrection: false,
    capability: 'RENDER_ONLY',
    printerLanguages: [],
    description: 'Circular projection of Code 93 for specialized specimen tops.',
  },
  {
    id: 'circularcode128',
    name: 'Circular Code 128',
    aliases: ['Radial 128'],
    category: 'Linear 1D',
    dimension: '1D',
    defaultData: 'RADIAL128',
    supportsVariableData: false,
    supportsHumanReadableText: false,
    supportsChecksum: false,
    supportsGS1: false,
    supportsErrorCorrection: false,
    capability: 'RENDER_ONLY',
    printerLanguages: [],
    description: 'Concentric ring projection of Code 128 for lab automation caps.',
  },
  {
    id: 'circularitf',
    name: 'Circular Interleaved 2 of 5',
    aliases: ['Radial ITF'],
    category: 'Linear 1D',
    dimension: '1D',
    defaultData: '12345678',
    supportsVariableData: false,
    supportsHumanReadableText: false,
    supportsChecksum: false,
    supportsGS1: false,
    supportsErrorCorrection: false,
    capability: 'RENDER_ONLY',
    printerLanguages: [],
    description: 'Circular projection of Interleaved 2 of 5 for spinning sample plates.',
  },

  // --- GS1 Family ---
  {
    id: 'gs1-128',
    name: 'GS1-128',
    aliases: ['EAN-128', 'UCC-128'],
    category: 'GS1',
    dimension: '1D',
    defaultData: '(01)07046261398572(17)261231(10)LOT9981',
    supportsVariableData: true,
    supportsHumanReadableText: true,
    supportsChecksum: true,
    supportsGS1: true,
    supportsErrorCorrection: false,
    capability: 'SUPPORTED',
    printerLanguages: ['ZPL', 'TSPL', 'EPL'],
    description: 'Supply-chain logistics barcode using Application Identifiers (AI) and FNC1 flag.',
  },
  {
    id: 'gs1-datamatrix',
    name: 'GS1 DataMatrix',
    aliases: ['GS1 2D DataMatrix'],
    category: 'GS1',
    dimension: '2D',
    defaultData: '(01)00312345678906(21)SN901234(17)271031(10)BATCH77',
    supportsVariableData: true,
    supportsHumanReadableText: false,
    supportsChecksum: true,
    supportsGS1: true,
    supportsErrorCorrection: true,
    capability: 'SUPPORTED',
    printerLanguages: ['ZPL', 'TSPL'],
    description: 'Mandatory pharmaceutical DSCSA & medical device UDI serialization symbol.',
  },
  {
    id: 'gs1-qrcode',
    name: 'GS1 QR Code',
    aliases: ['GS1 Digital Link QR'],
    category: 'GS1',
    dimension: '2D',
    defaultData: 'https://id.gs1.org/01/09521234543213/10/LOT42?17=281130',
    supportsVariableData: true,
    supportsHumanReadableText: false,
    supportsChecksum: true,
    supportsGS1: true,
    supportsErrorCorrection: true,
    capability: 'SUPPORTED',
    printerLanguages: ['ZPL', 'TSPL'],
    description: 'Sunrise 2027 point-of-sale and digital link interactive consumer QR standard.',
  },
  {
    id: 'gs1-composite',
    name: 'GS1 Composite',
    aliases: ['EAN.UCC Composite', 'CC-A', 'CC-B'],
    category: 'GS1',
    dimension: 'Composite',
    defaultData: '(01)00012345678905|(10)AB-12',
    supportsVariableData: true,
    supportsHumanReadableText: true,
    supportsChecksum: true,
    supportsGS1: true,
    supportsErrorCorrection: true,
    capability: 'PARTIAL',
    printerLanguages: ['ZPL'],
    description: 'Bi-directional composite symbol combining a linear base with a MicroPDF417 2D component.',
  },
  {
    id: 'rss',
    name: 'RSS',
    aliases: ['GS1 DataBar', 'Reduced Space Symbology'],
    category: 'GS1',
    dimension: '1D',
    defaultData: '(01)00012345678905',
    supportsVariableData: true,
    supportsHumanReadableText: true,
    supportsChecksum: true,
    supportsGS1: true,
    supportsErrorCorrection: false,
    capability: 'PARTIAL',
    printerLanguages: ['ZPL'],
    description: 'Used for loose produce pricing, coupons, and healthcare unit-dose tracking.',
  },

  // --- 2D / Matrix ---
  {
    id: 'qrcode',
    name: 'QR Code',
    aliases: ['Quick Response Code', 'Model 2 QR'],
    category: '2D Matrix',
    dimension: '2D',
    defaultData: 'https://labelforge.enterprise.sys/verify/LOT-88219',
    supportsVariableData: true,
    supportsHumanReadableText: false,
    supportsChecksum: true,
    supportsGS1: true,
    supportsErrorCorrection: true,
    capability: 'SUPPORTED',
    printerLanguages: ['ZPL', 'TSPL', 'EPL', 'CPCL'],
    description: 'High-speed 2D matrix symbology with Reed-Solomon error correction and omnidirectional scanning.',
  },
  {
    id: 'datamatrix',
    name: 'Data Matrix',
    aliases: ['ECC 200', 'ISO/IEC 16022'],
    category: '2D Matrix',
    dimension: '2D',
    defaultData: 'LF-DM-2026-X99',
    supportsVariableData: true,
    supportsHumanReadableText: false,
    supportsChecksum: true,
    supportsGS1: true,
    supportsErrorCorrection: true,
    capability: 'SUPPORTED',
    printerLanguages: ['ZPL', 'TSPL', 'EPL'],
    description: 'Compact 2D matrix with L-shaped finder pattern for high density small parts marking.',
  },
  {
    id: 'pdf417',
    name: 'PDF417',
    aliases: ['Portable Data File 417'],
    category: '2D Matrix',
    dimension: '2D',
    defaultData: 'AAMVA-DRIVER-LICENSE-DOC-8921-998877',
    supportsVariableData: true,
    supportsHumanReadableText: false,
    supportsChecksum: true,
    supportsGS1: false,
    supportsErrorCorrection: true,
    capability: 'SUPPORTED',
    printerLanguages: ['ZPL', 'TSPL', 'EPL'],
    description: 'Multi-row stacked 2D barcode capable of encoding over a kilobyte of biometric/transport data.',
  },
  {
    id: 'micropdf417',
    name: 'MicroPDF417',
    aliases: ['Micro PDF'],
    category: '2D Matrix',
    dimension: '2D',
    defaultData: 'MPDF-44021',
    supportsVariableData: true,
    supportsHumanReadableText: false,
    supportsChecksum: true,
    supportsGS1: true,
    supportsErrorCorrection: true,
    capability: 'SUPPORTED',
    printerLanguages: ['ZPL'],
    description: 'Compact 2D stacked barcode designed for items too small for standard PDF417.',
  },
  {
    id: 'compactpdf417',
    name: 'Compact PDF417',
    aliases: ['Truncated PDF417'],
    category: '2D Matrix',
    dimension: '2D',
    defaultData: 'CPDF-9982',
    supportsVariableData: true,
    supportsHumanReadableText: false,
    supportsChecksum: true,
    supportsGS1: false,
    supportsErrorCorrection: true,
    capability: 'PARTIAL',
    printerLanguages: ['ZPL'],
    description: 'PDF417 with omitted right-hand stop pattern for narrow print areas.',
  },
  {
    id: 'truncatedpdf417',
    name: 'Truncated PDF417',
    aliases: ['Narrow PDF417'],
    category: '2D Matrix',
    dimension: '2D',
    defaultData: 'TRUNC-PDF-11',
    supportsVariableData: true,
    supportsHumanReadableText: false,
    supportsChecksum: true,
    supportsGS1: false,
    supportsErrorCorrection: true,
    capability: 'PARTIAL',
    printerLanguages: ['ZPL'],
    description: 'Truncated variant minimizing overhead in clean scan environments.',
  },
  {
    id: 'azteccode',
    name: 'Aztec Code',
    aliases: ['ISO/IEC 24778'],
    category: '2D Matrix',
    dimension: '2D',
    defaultData: 'AZTEC-BOARDING-PASS-TKT99',
    supportsVariableData: true,
    supportsHumanReadableText: false,
    supportsChecksum: true,
    supportsGS1: false,
    supportsErrorCorrection: true,
    capability: 'SUPPORTED',
    printerLanguages: ['ZPL', 'TSPL'],
    description: '2D matrix with central bullseye target, standard in airline and railway mobile ticketing.',
  },
  {
    id: 'aztecrune',
    name: 'Aztec Rune',
    aliases: ['Compact Aztec Rune'],
    category: '2D Matrix',
    dimension: '2D',
    defaultData: '24',
    supportsVariableData: true,
    supportsHumanReadableText: false,
    supportsChecksum: true,
    supportsGS1: false,
    supportsErrorCorrection: true,
    capability: 'RENDER_ONLY',
    printerLanguages: [],
    description: 'Ultra-compact Aztec variant encoding numbers 0 to 255 for very small items.',
  },
  {
    id: 'maxicode',
    name: 'MaxiCode',
    aliases: ['UPS Code', 'Target Code'],
    category: '2D Matrix',
    dimension: '2D',
    defaultData: '084840123456789',
    supportsVariableData: true,
    supportsHumanReadableText: false,
    supportsChecksum: true,
    supportsGS1: false,
    supportsErrorCorrection: true,
    capability: 'PARTIAL',
    printerLanguages: ['ZPL'],
    description: 'Fixed-size honeycomb matrix with central finder bullseye used on UPS package labels.',
  },
  {
    id: 'microqrcode',
    name: 'Micro QR Code',
    aliases: ['Micro QR'],
    category: '2D Matrix',
    dimension: '2D',
    defaultData: 'MQR-1234',
    supportsVariableData: true,
    supportsHumanReadableText: false,
    supportsChecksum: true,
    supportsGS1: false,
    supportsErrorCorrection: true,
    capability: 'SUPPORTED',
    printerLanguages: ['ZPL'],
    description: 'Single position detection pattern QR variant for micro circuit boards and watches.',
  },
  {
    id: 'iqrcode',
    name: 'iQR Code',
    aliases: ['Rectangular QR'],
    category: '2D Matrix',
    dimension: '2D',
    defaultData: 'IQR-RECT-8812',
    supportsVariableData: true,
    supportsHumanReadableText: false,
    supportsChecksum: true,
    supportsGS1: false,
    supportsErrorCorrection: true,
    capability: 'PARTIAL',
    printerLanguages: [],
    description: 'Rectangular matrix extension of QR code for narrow aspect ratio printing.',
  },
  {
    id: 'dotcode',
    name: 'DotCode',
    aliases: ['Optical Dot Matrix'],
    category: '2D Matrix',
    dimension: '2D',
    defaultData: 'DOTCODE-TOBACCO-TRACK',
    supportsVariableData: true,
    supportsHumanReadableText: false,
    supportsChecksum: true,
    supportsGS1: true,
    supportsErrorCorrection: true,
    capability: 'PARTIAL',
    printerLanguages: ['ZPL'],
    description: 'Disconnected dot pattern matrix optimized for high-speed continuous inkjet printers.',
  },
  {
    id: 'gridmatrix',
    name: 'Grid Matrix',
    aliases: ['Chinese Grid Matrix'],
    category: '2D Matrix',
    dimension: '2D',
    defaultData: 'GRIDMATRIX-902',
    supportsVariableData: true,
    supportsHumanReadableText: false,
    supportsChecksum: true,
    supportsGS1: false,
    supportsErrorCorrection: true,
    capability: 'RENDER_ONLY',
    printerLanguages: [],
    description: '2D matrix barcode standard optimized for Chinese characters and digits.',
  },
  {
    id: 'hanxincode',
    name: 'Han Xin Code',
    aliases: ['Chinese Sensible Code'],
    category: '2D Matrix',
    dimension: '2D',
    defaultData: 'HANXIN-CHINESE-STANDARD',
    supportsVariableData: true,
    supportsHumanReadableText: false,
    supportsChecksum: true,
    supportsGS1: false,
    supportsErrorCorrection: true,
    capability: 'RENDER_ONLY',
    printerLanguages: [],
    description: 'National Chinese 2D matrix symbology designed for multi-byte Unicode and tax stamps.',
  },

  // --- Postal Family ---
  {
    id: 'usps-imb',
    name: 'USPS Intelligent Mail',
    aliases: ['OneCode', '4-State Customer Barcode'],
    category: 'Postal',
    dimension: 'Postal',
    defaultData: '01234567890123456789',
    supportsVariableData: true,
    supportsHumanReadableText: false,
    supportsChecksum: true,
    supportsGS1: false,
    supportsErrorCorrection: false,
    capability: 'SUPPORTED',
    printerLanguages: ['ZPL'],
    description: 'United States Postal Service 4-state height-modulated barcode for letter automation.',
  },
  {
    id: 'usps-postnet',
    name: 'USPS Postnet',
    aliases: ['Postal Numeric Encoding Technique'],
    category: 'Postal',
    dimension: 'Postal',
    defaultData: '902101234',
    supportsVariableData: true,
    supportsHumanReadableText: false,
    supportsChecksum: true,
    supportsGS1: false,
    supportsErrorCorrection: false,
    capability: 'SUPPORTED',
    printerLanguages: ['ZPL'],
    description: 'Legacy US postal routing barcode encoding 5, 9, or 11 digit ZIP codes.',
  },
  {
    id: 'usps-planet',
    name: 'USPS Planet',
    aliases: ['Postal Alpha Numeric Encoding Technique'],
    category: 'Postal',
    dimension: 'Postal',
    defaultData: '401234567891',
    supportsVariableData: true,
    supportsHumanReadableText: false,
    supportsChecksum: true,
    supportsGS1: false,
    supportsErrorCorrection: false,
    capability: 'SUPPORTED',
    printerLanguages: ['ZPL'],
    description: 'Legacy USPS confirmation and mailpiece tracking barcode.',
  },
  {
    id: 'royalmail-cbc',
    name: 'Royal Mail Customer Bar Code',
    aliases: ['RM4SCC'],
    category: 'Postal',
    dimension: 'Postal',
    defaultData: 'SN34RD1A',
    supportsVariableData: true,
    supportsHumanReadableText: false,
    supportsChecksum: true,
    supportsGS1: false,
    supportsErrorCorrection: false,
    capability: 'SUPPORTED',
    printerLanguages: ['ZPL'],
    description: 'British Royal Mail 4-state customer barcode with descender, ascender, and tracker bars.',
  },
  {
    id: 'royalmail-mailmark-c',
    name: 'Royal Mail 4 State Mailmark Type C',
    aliases: ['Mailmark Type C'],
    category: 'Postal',
    dimension: 'Postal',
    defaultData: 'JGB 12345678',
    supportsVariableData: true,
    supportsHumanReadableText: false,
    supportsChecksum: true,
    supportsGS1: false,
    supportsErrorCorrection: false,
    capability: 'SUPPORTED',
    printerLanguages: ['ZPL'],
    description: 'UK modern Mailmark 4-state barcode with high precision tracking data.',
  },
  {
    id: 'royalmail-mailmark-l',
    name: 'Royal Mail 4 State Mailmark Type L',
    aliases: ['Mailmark Type L'],
    category: 'Postal',
    dimension: 'Postal',
    defaultData: 'JGB 87654321',
    supportsVariableData: true,
    supportsHumanReadableText: false,
    supportsChecksum: true,
    supportsGS1: false,
    supportsErrorCorrection: false,
    capability: 'SUPPORTED',
    printerLanguages: ['ZPL'],
    description: 'Type L format for large envelopes and automated sorting systems.',
  },
  {
    id: 'royalmail-cmdm',
    name: 'Royal Mail CMDM Mailmark',
    aliases: ['Mailmark 2D Complex'],
    category: 'Postal',
    dimension: '2D',
    defaultData: 'CMDM-MAILMARK-DATA-99',
    supportsVariableData: true,
    supportsHumanReadableText: false,
    supportsChecksum: true,
    supportsGS1: false,
    supportsErrorCorrection: true,
    capability: 'PARTIAL',
    printerLanguages: ['ZPL'],
    description: 'Royal Mail 2D Data Matrix format for publishing and bulk mailings.',
  },
  {
    id: 'australiapost',
    name: 'Australia Post',
    aliases: ['AusPost 4-State'],
    category: 'Postal',
    dimension: 'Postal',
    defaultData: '11395493012',
    supportsVariableData: true,
    supportsHumanReadableText: false,
    supportsChecksum: true,
    supportsGS1: false,
    supportsErrorCorrection: false,
    capability: 'SUPPORTED',
    printerLanguages: ['ZPL'],
    description: 'Australian domestic postal barcode with sorting code and customer info.',
  },
  {
    id: 'japanesepost',
    name: 'Japanese Post',
    aliases: ['Japan Post 4-State'],
    category: 'Postal',
    dimension: 'Postal',
    defaultData: '15400233-16-4',
    supportsVariableData: true,
    supportsHumanReadableText: false,
    supportsChecksum: true,
    supportsGS1: false,
    supportsErrorCorrection: false,
    capability: 'SUPPORTED',
    printerLanguages: ['ZPL'],
    description: 'Customer barcode standard for automated mail sorting across Japan.',
  },
  {
    id: 'kixcode',
    name: 'KIX Code',
    aliases: ['Dutch Post', 'PostNL KIX'],
    category: 'Postal',
    dimension: 'Postal',
    defaultData: '1234AB10X',
    supportsVariableData: true,
    supportsHumanReadableText: false,
    supportsChecksum: false,
    supportsGS1: false,
    supportsErrorCorrection: false,
    capability: 'SUPPORTED',
    printerLanguages: ['ZPL'],
    description: 'Netherlands postal service 4-state routing barcode without start/stop bars.',
  },
  {
    id: 'koreapost',
    name: 'Korea Post',
    aliases: ['Korean Postal Barcode'],
    category: 'Postal',
    dimension: 'Postal',
    defaultData: '123456',
    supportsVariableData: true,
    supportsHumanReadableText: false,
    supportsChecksum: true,
    supportsGS1: false,
    supportsErrorCorrection: false,
    capability: 'PARTIAL',
    printerLanguages: ['ZPL'],
    description: 'South Korea Post 6-digit postal code sorting symbology.',
  },
  {
    id: 'singaporepost',
    name: 'Singapore Post',
    aliases: ['SingPost 4-State'],
    category: 'Postal',
    dimension: 'Postal',
    defaultData: '569874',
    supportsVariableData: true,
    supportsHumanReadableText: false,
    supportsChecksum: true,
    supportsGS1: false,
    supportsErrorCorrection: false,
    capability: 'SUPPORTED',
    printerLanguages: ['ZPL'],
    description: 'Singapore national 6-digit delivery point barcode.',
  },
  {
    id: 'deutschepost-identcode',
    name: 'Deutsche Post Identcode',
    aliases: ['DHL Identcode'],
    category: 'Postal',
    dimension: '1D',
    defaultData: '56400063473',
    supportsVariableData: true,
    supportsHumanReadableText: true,
    supportsChecksum: true,
    supportsGS1: false,
    supportsErrorCorrection: false,
    capability: 'SUPPORTED',
    printerLanguages: ['ZPL'],
    description: 'Deutsche Post / DHL parcel logistics tracking barcode based on Interleaved 2 of 5.',
  },
  {
    id: 'deutschepost-leitcode',
    name: 'Deutsche Post Leticode',
    aliases: ['DHL Leitcode'],
    category: 'Postal',
    dimension: '1D',
    defaultData: '2134807541289',
    supportsVariableData: true,
    supportsHumanReadableText: true,
    supportsChecksum: true,
    supportsGS1: false,
    supportsErrorCorrection: false,
    capability: 'SUPPORTED',
    printerLanguages: ['ZPL'],
    description: 'Routing barcode for automatic mail sorting throughout Germany.',
  },
  {
    id: 'canadiancustoms',
    name: 'Canadian Customs',
    aliases: ['CBSA Barcode'],
    category: 'Postal',
    dimension: '1D',
    defaultData: 'PARS991288',
    supportsVariableData: true,
    supportsHumanReadableText: true,
    supportsChecksum: false,
    supportsGS1: false,
    supportsErrorCorrection: false,
    capability: 'SUPPORTED',
    printerLanguages: ['ZPL'],
    description: 'Canada Border Services Agency Pre-Arrival Review System (PARS) cargo clearance.',
  },
  {
    id: 'cepnet',
    name: 'CEPNet (Brasil)',
    aliases: ['Correios CEPNet'],
    category: 'Postal',
    dimension: 'Postal',
    defaultData: '01001-000',
    supportsVariableData: true,
    supportsHumanReadableText: true,
    supportsChecksum: true,
    supportsGS1: false,
    supportsErrorCorrection: false,
    capability: 'PARTIAL',
    printerLanguages: ['ZPL'],
    description: 'Brazilian Correios postal automation barcode for CEP distribution.',
  },
  {
    id: 'ppn',
    name: 'PPN',
    aliases: ['Pharmacy Product Number'],
    category: 'Specialized',
    dimension: '2D',
    defaultData: '1100012345678901',
    supportsVariableData: true,
    supportsHumanReadableText: false,
    supportsChecksum: true,
    supportsGS1: false,
    supportsErrorCorrection: true,
    capability: 'SUPPORTED',
    printerLanguages: ['ZPL'],
    description: 'IFA European pharmaceutical serialization and track-and-trace format.',
  },

  // --- General / Proprietary / Specialized ---
  {
    id: 'ankerplessey',
    name: 'Anker Plessey',
    aliases: ['Anker Data Barcode'],
    category: 'Specialized',
    dimension: '1D',
    defaultData: '994411',
    supportsVariableData: true,
    supportsHumanReadableText: true,
    supportsChecksum: true,
    supportsGS1: false,
    supportsErrorCorrection: false,
    capability: 'PARTIAL',
    printerLanguages: [],
    description: 'Proprietary cash register and point-of-sale scanner barcode.',
  },
  {
    id: 'bc412',
    name: 'BC412',
    aliases: ['SEMI T1-95'],
    category: 'Specialized',
    dimension: '1D',
    defaultData: 'WAFER9021',
    supportsVariableData: true,
    supportsHumanReadableText: true,
    supportsChecksum: true,
    supportsGS1: false,
    supportsErrorCorrection: false,
    capability: 'SUPPORTED',
    printerLanguages: ['ZPL'],
    description: 'Semiconductor industry standard for silicon wafer marking and tracking.',
  },
  {
    id: 'channelcode',
    name: 'Channel Code',
    aliases: ['Channel 3 to 8'],
    category: 'Specialized',
    dimension: '1D',
    defaultData: '74125',
    supportsVariableData: true,
    supportsHumanReadableText: true,
    supportsChecksum: false,
    supportsGS1: false,
    supportsErrorCorrection: false,
    capability: 'RENDER_ONLY',
    printerLanguages: [],
    description: 'Extremely high-density variable-length numeric barcode format.',
  },
  {
    id: 'codablockf',
    name: 'CodaBlock F',
    aliases: ['Stacked Code 128'],
    category: 'Specialized',
    dimension: '2D',
    defaultData: 'CODABLOCK-F-ROW-1-DATA',
    supportsVariableData: true,
    supportsHumanReadableText: false,
    supportsChecksum: true,
    supportsGS1: false,
    supportsErrorCorrection: false,
    capability: 'PARTIAL',
    printerLanguages: ['ZPL'],
    description: 'Multi-row stacked version of Code 128 developed in Germany.',
  },
  {
    id: 'code16k',
    name: 'Code 16K',
    aliases: ['USS-16K'],
    category: 'Specialized',
    dimension: '2D',
    defaultData: 'CODE16K-9901',
    supportsVariableData: true,
    supportsHumanReadableText: false,
    supportsChecksum: true,
    supportsGS1: false,
    supportsErrorCorrection: false,
    capability: 'PARTIAL',
    printerLanguages: ['ZPL'],
    description: 'Stacked 16-row barcode based on Code 128 subsets for small medical items.',
  },
  {
    id: 'code49',
    name: 'Code 49',
    aliases: ['USS-49'],
    category: 'Specialized',
    dimension: '2D',
    defaultData: 'CODE49-DATA',
    supportsVariableData: true,
    supportsHumanReadableText: false,
    supportsChecksum: true,
    supportsGS1: false,
    supportsErrorCorrection: false,
    capability: 'PARTIAL',
    printerLanguages: ['ZPL'],
    description: 'Early ultra-compact stacked symbology encoding 2 to 8 rows.',
  },
  {
    id: 'composite',
    name: 'Composite',
    aliases: ['EAN.UCC Composite General'],
    category: 'Specialized',
    dimension: 'Composite',
    defaultData: 'COMPOSITE-LINK-SYMBOL',
    supportsVariableData: true,
    supportsHumanReadableText: true,
    supportsChecksum: true,
    supportsGS1: true,
    supportsErrorCorrection: true,
    capability: 'PARTIAL',
    printerLanguages: ['ZPL'],
    description: 'Generic composite multi-component symbol linking linear and 2D components.',
  },
  {
    id: 'posicodea',
    name: 'PosiCode A',
    aliases: ['Position Code A'],
    category: 'Specialized',
    dimension: '1D',
    defaultData: 'POSI-A-102',
    supportsVariableData: true,
    supportsHumanReadableText: false,
    supportsChecksum: true,
    supportsGS1: false,
    supportsErrorCorrection: false,
    capability: 'RENDER_ONLY',
    printerLanguages: [],
    description: 'Matrix bar position code variant A for high-speed automated sorting.',
  },
  {
    id: 'posicodeb',
    name: 'PosiCode B',
    aliases: ['Position Code B'],
    category: 'Specialized',
    dimension: '1D',
    defaultData: 'POSI-B-204',
    supportsVariableData: true,
    supportsHumanReadableText: false,
    supportsChecksum: true,
    supportsGS1: false,
    supportsErrorCorrection: false,
    capability: 'RENDER_ONLY',
    printerLanguages: [],
    description: 'PosiCode variant B with alternate position parity layout.',
  },
  {
    id: 'posicodelimiteda',
    name: 'PosiCode Limited A',
    aliases: ['Limited PosiCode A'],
    category: 'Specialized',
    dimension: '1D',
    defaultData: 'LIM-A-88',
    supportsVariableData: true,
    supportsHumanReadableText: false,
    supportsChecksum: true,
    supportsGS1: false,
    supportsErrorCorrection: false,
    capability: 'RENDER_ONLY',
    printerLanguages: [],
    description: 'Limited height variant of PosiCode A for small packaging.',
  },
  {
    id: 'posicodelimitedb',
    name: 'PosiCode Limited B',
    aliases: ['Limited PosiCode B'],
    category: 'Specialized',
    dimension: '1D',
    defaultData: 'LIM-B-99',
    supportsVariableData: true,
    supportsHumanReadableText: false,
    supportsChecksum: true,
    supportsGS1: false,
    supportsErrorCorrection: false,
    capability: 'RENDER_ONLY',
    printerLanguages: [],
    description: 'Limited height variant of PosiCode B.',
  },
  {
    id: 'trioptic',
    name: 'Trioptic',
    aliases: ['Trioptic Code 39'],
    category: 'Specialized',
    dimension: '1D',
    defaultData: '012ABC',
    supportsVariableData: true,
    supportsHumanReadableText: true,
    supportsChecksum: true,
    supportsGS1: false,
    supportsErrorCorrection: false,
    capability: 'SUPPORTED',
    printerLanguages: ['ZPL'],
    description: 'Standard 6-character barcode specifically for magnetic tape library cartridges.',
    characterSetHint: 'Exactly 6 characters',
  },
  {
    id: 'tlc39',
    name: 'TLC39',
    aliases: ['TCIF Linked Code 39'],
    category: 'Specialized',
    dimension: 'Composite',
    defaultData: '0123456789',
    supportsVariableData: true,
    supportsHumanReadableText: true,
    supportsChecksum: true,
    supportsGS1: false,
    supportsErrorCorrection: true,
    capability: 'PARTIAL',
    printerLanguages: ['ZPL'],
    description: 'Telecommunications Industry Forum standard combining Code 39 with MicroPDF417.',
  },
  {
    id: 'tlc39micropdf',
    name: 'TLC39 MicroPDF417',
    aliases: ['TLC39 2D component'],
    category: 'Specialized',
    dimension: 'Composite',
    defaultData: 'TLC39-LINK-MPDF',
    supportsVariableData: true,
    supportsHumanReadableText: false,
    supportsChecksum: true,
    supportsGS1: false,
    supportsErrorCorrection: true,
    capability: 'PARTIAL',
    printerLanguages: ['ZPL'],
    description: 'The 2D MicroPDF417 upper component of the TLC39 telecommunications standard.',
  },
];

/** Quick lookup map by ID or alias */
export const SYMBOLOGY_MAP = new Map<string, BarcodeSymbologyDefinition>();
BARCODE_SYMBOLOGIES.forEach((sym) => {
  SYMBOLOGY_MAP.set(sym.id.toLowerCase(), sym);
  sym.aliases.forEach((alias) => {
    SYMBOLOGY_MAP.set(alias.toLowerCase(), sym);
  });
});

export function getSymbologyById(id: string): BarcodeSymbologyDefinition {
  const found = SYMBOLOGY_MAP.get(id.toLowerCase());
  return found || SYMBOLOGY_MAP.get('code128')!;
}
