/**
 * Enterprise Industry Label Presets
 * Pre-engineered templates for logistics, healthcare, asset management, and retail.
 */

import { LabelDocument } from '../types';

export const TEMPLATE_PRESETS: LabelDocument[] = [
  {
    id: 'preset-gs1-logistics',
    name: 'GS1 Logistics Pallet Label',
    description: 'Standard 4" x 6" (101.6 x 152.4 mm) shipping container label with SSCC-18, GTIN, Lot, and Expiry.',
    version: '1.0.0',
    width: 101.6,
    height: 152.4,
    unit: 'mm',
    dpi: 203,
    orientation: 'portrait',
    cornerRadius: 1.5,
    margins: { top: 3, left: 3, right: 3, bottom: 3 },
    backgroundColor: '#ffffff',
    variables: {
      SHIP_TO_NAME: 'GLOBAL SUPPLY DEPOT #4',
      DESTINATION: 'CHICAGO DISTRIBUTION CTR, IL 60607',
      PO_NUMBER: 'PO-984210',
      SSCC: '(00)008432100000000427',
      GTIN: '(01)10843210000045',
      LOT: 'LOT-2026-AUG',
      EXPIRY: '2028-12-31',
      QTY: '1,440 EA',
    },
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
    objects: [
      {
        id: 'box-header',
        name: 'Header Box',
        type: 'shape',
        shapeType: 'rounded',
        x: 4,
        y: 4,
        width: 93.6,
        height: 28,
        strokeColor: '#000000',
        strokeWidth: 0.6,
        fillColor: '#ffffff',
        cornerRadius: 1,
        rotation: 0,
        zIndex: 1,
        locked: false,
        hidden: false,
      },
      {
        id: 'txt-ship-label',
        name: 'Ship To Header',
        type: 'text',
        text: 'SHIP TO / DELIVER TO:',
        fontSize: 8,
        fontFamily: 'Plus Jakarta Sans',
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#000000',
        x: 6,
        y: 6,
        width: 80,
        height: 4,
        rotation: 0,
        zIndex: 2,
        locked: false,
        hidden: false,
      },
      {
        id: 'txt-sscc-title',
        name: 'SSCC Title',
        type: 'text',
        text: 'SERIAL SHIPPING CONTAINER CODE (SSCC-18):',
        fontSize: 9,
        fontFamily: 'Plus Jakarta Sans',
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#000000',
        x: 6,
        y: 11,
        width: 90,
        height: 5,
        rotation: 0,
        zIndex: 3,
        locked: false,
        hidden: false,
      },
      {
        id: 'txt-dest-addr',
        name: 'Destination Address',
        type: 'text',
        text: '{{DESTINATION}}',
        fontSize: 9,
        fontFamily: 'Plus Jakarta Sans',
        fontWeight: '500',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#000000',
        x: 6,
        y: 18,
        width: 90,
        height: 5,
        rotation: 0,
        zIndex: 4,
        locked: false,
        hidden: false,
      },
      {
        id: 'txt-ship-name',
        name: 'Destination Name',
        type: 'text',
        text: '{{SHIP_TO_NAME}}',
        fontSize: 12,
        fontFamily: 'Plus Jakarta Sans',
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#000000',
        x: 135,
        y: 22,
        width: 90,
        height: 6,
        rotation: 0,
        zIndex: 5,
        locked: false,
        hidden: false,
      },
      // Middle Section - GTIN Barcode
      {
        id: 'bar-gtin',
        name: 'GTIN-14 Barcode',
        type: 'barcode',
        symbologyId: 'gs1-128',
        data: '(01)10843210000045(17)281231(10)LOT26A',
        showHumanReadable: true,
        humanReadablePosition: 'bottom',
        humanReadableFontSize: 8,
        includeCheckDigit: true,
        quietZoneMm: 2,
        color: '#000000',
        backgroundColor: '#ffffff',
        x: 6,
        y: 36,
        width: 89.6,
        height: 25,
        rotation: 0,
        zIndex: 6,
        locked: false,
        hidden: false,
      },
      {
        id: 'div-line',
        name: 'Divider Line',
        type: 'shape',
        shapeType: 'line',
        x: 4,
        y: 66,
        width: 93.6,
        height: 0.5,
        strokeColor: '#000000',
        strokeWidth: 0.5,
        fillColor: '#000000',
        cornerRadius: 0,
        rotation: 0,
        zIndex: 7,
        locked: false,
        hidden: false,
      },
      // SSCC Section
      {
        id: 'txt-po-num',
        name: 'PO Number Text',
        type: 'text',
        text: 'PO: {{PO_NUMBER}} | QTY: {{QTY}}',
        fontSize: 9,
        fontFamily: 'JetBrains Mono',
        fontWeight: '600',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#000000',
        x: 6,
        y: 70,
        width: 88,
        height: 5,
        rotation: 0,
        zIndex: 8,
        locked: false,
        hidden: false,
      },
      {
        id: 'bar-sscc',
        name: 'SSCC-18 Barcode',
        type: 'barcode',
        symbologyId: 'code128',
        data: '(00)008432100000000427',
        showHumanReadable: true,
        humanReadablePosition: 'bottom',
        humanReadableFontSize: 10,
        includeCheckDigit: true,
        quietZoneMm: 3,
        color: '#000000',
        backgroundColor: '#ffffff',
        x: 6,
        y: 78,
        width: 89.6,
        height: 38,
        rotation: 0,
        zIndex: 9,
        locked: false,
        hidden: false,
      },
      {
        id: 'qr-digital-link',
        name: 'GS1 Digital Link QR',
        type: 'qrcode',
        data: 'https://id.gs1.org/01/10843210000045/21/SN000427',
        errorCorrection: 'M',
        color: '#000000',
        backgroundColor: '#ffffff',
        x: 6,
        y: 122,
        width: 24,
        height: 24,
        rotation: 0,
        zIndex: 10,
        locked: false,
        hidden: false,
      },
      {
        id: 'txt-qr-caption',
        name: 'Digital Link Note',
        type: 'text',
        text: 'Scan for e-Bill of Lading & Inspection Report',
        fontSize: 8,
        fontFamily: 'Plus Jakarta Sans',
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#333333',
        x: 33,
        y: 128,
        width: 60,
        height: 6,
        rotation: 0,
        zIndex: 11,
        locked: false,
        hidden: false,
      },
      {
        id: 'cnt-pallet-num',
        name: 'Pallet Sequence Counter',
        type: 'counter',
        prefix: 'PALLET #',
        suffix: ' OF 24',
        currentValue: 1,
        startValue: 1,
        step: 1,
        padding: 2,
        fontSize: 10,
        fontFamily: 'JetBrains Mono',
        fontWeight: 'bold',
        color: '#000000',
        x: 33,
        y: 138,
        width: 55,
        height: 6,
        rotation: 0,
        zIndex: 12,
        locked: false,
        hidden: false,
      },
    ],
  },

  {
    id: 'preset-pharma-vial',
    name: 'Pharmaceutical DSCSA Vial Label',
    description: 'Compliant 50 x 25 mm healthcare label with GS1 DataMatrix ECC200, Rx details, and expiration date.',
    version: '1.0.0',
    width: 50,
    height: 25,
    unit: 'mm',
    dpi: 300,
    orientation: 'landscape',
    cornerRadius: 1.0,
    margins: { top: 1.5, left: 1.5, right: 1.5, bottom: 1.5 },
    backgroundColor: '#ffffff',
    variables: {
      DRUG_NAME: 'Atorvastatin 20mg',
      NDC: 'NDC 0071-0156-23',
      BATCH: 'BTH-88219',
      EXP: '2028-09',
      SERIAL: 'SN-049210',
    },
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
    objects: [
      {
        id: 'txt-drug',
        name: 'Drug Name',
        type: 'text',
        text: '{{DRUG_NAME}}',
        fontSize: 10,
        fontFamily: 'Plus Jakarta Sans',
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#000000',
        x: 2,
        y: 2,
        width: 32,
        height: 5,
        rotation: 0,
        zIndex: 1,
        locked: false,
        hidden: false,
      },
      {
        id: 'txt-ndc',
        name: 'NDC Code',
        type: 'text',
        text: '{{NDC}} | Oral Tablet',
        fontSize: 7,
        fontFamily: 'JetBrains Mono',
        fontWeight: '600',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#222222',
        x: 2,
        y: 7.5,
        width: 32,
        height: 4,
        rotation: 0,
        zIndex: 2,
        locked: false,
        hidden: false,
      },
      {
        id: 'txt-lot-exp',
        name: 'Lot & Exp',
        type: 'text',
        text: 'LOT: {{BATCH}}  EXP: {{EXP}}',
        fontSize: 6.5,
        fontFamily: 'JetBrains Mono',
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#000000',
        x: 2,
        y: 12,
        width: 32,
        height: 3.5,
        rotation: 0,
        zIndex: 3,
        locked: false,
        hidden: false,
      },
      {
        id: 'cnt-rx-serial',
        name: 'Serial Number Counter',
        type: 'counter',
        prefix: 'SN: ',
        suffix: '',
        currentValue: 10420,
        startValue: 10420,
        step: 1,
        padding: 6,
        fontSize: 6.5,
        fontFamily: 'JetBrains Mono',
        fontWeight: 'bold',
        color: '#000000',
        x: 2,
        y: 16,
        width: 32,
        height: 3.5,
        rotation: 0,
        zIndex: 4,
        locked: false,
        hidden: false,
      },
      {
        id: 'txt-rx-warn',
        name: 'Rx Only Warning',
        type: 'text',
        text: 'Rx ONLY - KEEP OUT OF REACH OF CHILDREN',
        fontSize: 5,
        fontFamily: 'Plus Jakarta Sans',
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#555555',
        x: 2,
        y: 20.5,
        width: 32,
        height: 3,
        rotation: 0,
        zIndex: 5,
        locked: false,
        hidden: false,
      },
      {
        id: 'dm-dscsa',
        name: 'GS1 DataMatrix 2D',
        type: 'datamatrix',
        data: '(01)00300710156238(21)10420(17)280930(10)BTH88219',
        format: 'square',
        color: '#000000',
        backgroundColor: '#ffffff',
        x: 34,
        y: 3,
        width: 14,
        height: 14,
        rotation: 0,
        zIndex: 6,
        locked: false,
        hidden: false,
      },
      {
        id: 'txt-dm-label',
        name: '2D Human Readable',
        type: 'text',
        text: 'GS1 2D UDI',
        fontSize: 5,
        fontFamily: 'JetBrains Mono',
        fontWeight: '600',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#444444',
        x: 34,
        y: 18.5,
        width: 14,
        height: 3,
        rotation: 0,
        zIndex: 7,
        locked: false,
        hidden: false,
      },
    ],
  },

  {
    id: 'preset-asset-tracking',
    name: 'Asset Tag & Hardware Inventory',
    description: 'Durable 70 x 36 mm polyester asset barcode tag with high-contrast Code 128 and property ID.',
    version: '1.0.0',
    width: 70,
    height: 36,
    unit: 'mm',
    dpi: 300,
    orientation: 'landscape',
    cornerRadius: 2.0,
    margins: { top: 2, left: 2, right: 2, bottom: 2 },
    backgroundColor: '#ffffff',
    variables: {
      ORG_NAME: 'ENTERPRISE TECH CORP',
      ASSET_NAME: 'MacBook Pro 16" M3 Max',
      DEPT: 'ENG-INFRA',
    },
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
    objects: [
      {
        id: 'tag-border',
        name: 'Outer Border',
        type: 'shape',
        shapeType: 'rounded',
        x: 2,
        y: 2,
        width: 66,
        height: 32,
        strokeColor: '#000000',
        strokeWidth: 0.5,
        fillColor: '#ffffff',
        cornerRadius: 1.5,
        rotation: 0,
        zIndex: 1,
        locked: false,
        hidden: false,
      },
      {
        id: 'txt-org',
        name: 'Org Header',
        type: 'text',
        text: 'PROPERTY OF {{ORG_NAME}}',
        fontSize: 7.5,
        fontFamily: 'Plus Jakarta Sans',
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#000000',
        x: 4,
        y: 3.5,
        width: 62,
        height: 4,
        rotation: 0,
        zIndex: 2,
        locked: false,
        hidden: false,
      },
      {
        id: 'bar-asset',
        name: 'Asset Code 128',
        type: 'barcode',
        symbologyId: 'code128',
        data: 'AST-2026-00481',
        showHumanReadable: true,
        humanReadablePosition: 'bottom',
        humanReadableFontSize: 8,
        includeCheckDigit: true,
        quietZoneMm: 2,
        color: '#000000',
        backgroundColor: '#ffffff',
        x: 5,
        y: 8,
        width: 44,
        height: 18,
        rotation: 0,
        zIndex: 3,
        locked: false,
        hidden: false,
      },
      {
        id: 'qr-asset',
        name: 'Asset QR Code',
        type: 'qrcode',
        data: 'https://assets.internal.corp/item/AST-2026-00481',
        errorCorrection: 'M',
        color: '#000000',
        backgroundColor: '#ffffff',
        x: 51,
        y: 9,
        width: 15,
        height: 15,
        rotation: 0,
        zIndex: 4,
        locked: false,
        hidden: false,
      },
      {
        id: 'txt-asset-warn',
        name: 'Warning Label',
        type: 'text',
        text: 'DO NOT REMOVE | REPORT LOST TO IT SEC EXT 411',
        fontSize: 5,
        fontFamily: 'JetBrains Mono',
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#222222',
        x: 4,
        y: 28,
        width: 62,
        height: 3.5,
        rotation: 0,
        zIndex: 5,
        locked: false,
        hidden: false,
      },
    ],
  },

  {
    id: 'preset-retail-price',
    name: 'Retail Shelf Edge Price Tag',
    description: '50 x 30 mm retail tag with prominent bold price, description, and EAN-13 / UPC-A barcode.',
    version: '1.0.0',
    width: 50,
    height: 30,
    unit: 'mm',
    dpi: 203,
    orientation: 'landscape',
    cornerRadius: 1.0,
    margins: { top: 1, left: 1, right: 1, bottom: 1 },
    backgroundColor: '#ffffff',
    variables: {
      ITEM_DESC: 'ORGANIC COLOMBIAN COFFEE 12OZ',
      PRICE: '$14.99',
      UNIT_PRICE: '$1.25 / oz',
      SKU: 'SKU-882194',
    },
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
    objects: [
      {
        id: 'txt-item-name',
        name: 'Item Description',
        type: 'text',
        text: '{{ITEM_DESC}}',
        fontSize: 7.5,
        fontFamily: 'Plus Jakarta Sans',
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#000000',
        x: 2,
        y: 2,
        width: 46,
        height: 4.5,
        rotation: 0,
        zIndex: 1,
        locked: false,
        hidden: false,
      },
      {
        id: 'txt-price',
        name: 'Main Price',
        type: 'text',
        text: '{{PRICE}}',
        fontSize: 16,
        fontFamily: 'Plus Jakarta Sans',
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#000000',
        x: 2,
        y: 7,
        width: 25,
        height: 9,
        rotation: 0,
        zIndex: 2,
        locked: false,
        hidden: false,
      },
      {
        id: 'txt-unit-price',
        name: 'Unit Price',
        type: 'text',
        text: '{{UNIT_PRICE}}',
        fontSize: 6.5,
        fontFamily: 'Plus Jakarta Sans',
        fontWeight: '500',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#444444',
        x: 28,
        y: 8.5,
        width: 20,
        height: 4,
        rotation: 0,
        zIndex: 3,
        locked: false,
        hidden: false,
      },
      {
        id: 'txt-sku',
        name: 'SKU Reference',
        type: 'text',
        text: '{{SKU}}',
        fontSize: 6,
        fontFamily: 'JetBrains Mono',
        fontWeight: '600',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#555555',
        x: 28,
        y: 12.5,
        width: 20,
        height: 3.5,
        rotation: 0,
        zIndex: 4,
        locked: false,
        hidden: false,
      },
      {
        id: 'bar-upc',
        name: 'EAN-13 Retail Barcode',
        type: 'barcode',
        symbologyId: 'ean13',
        data: '5901234123457',
        showHumanReadable: true,
        humanReadablePosition: 'bottom',
        humanReadableFontSize: 7.5,
        includeCheckDigit: true,
        quietZoneMm: 2,
        color: '#000000',
        backgroundColor: '#ffffff',
        x: 3,
        y: 16.5,
        width: 44,
        height: 12,
        rotation: 0,
        zIndex: 5,
        locked: false,
        hidden: false,
      },
    ],
  },
];
